apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - namespace.yaml
  - postgres-configmap.yaml
  - secrets.yaml
  - postgres-pvc.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - keycloak-statefulset.yaml
  - keycloak-service.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: keycloak-stack